
communism_key_words = {
    "anticapitlismo":5,
    "comunismo": 5,
    "comunista": 5,
    "comunistas": 5,
    "socialismo":4,
    "socialista":4,
    "revolución":3,
    "marxismo":3,
    "burguesía":3,
    "antiimperialismo":2,
    "anticapitalismo":4,
    "anticapitalista":4,
    "dictador":3,
    "dictadura":3,
    "obrero":2,
    "obreros":2,
    "burocracia":2,
    "estado":1,
    "política":1,
    "lenismo":3,
    "marxismo-leninismo":2,
    "revolucionario":2,
    "doctrina":1,
    "soviético":1,
    "urss":1,
    "materialismo":1,
    "anarquismo":1,
    "sociales":1,
    "burgués":1,
    "nacional":1,
    "totalitario":2,
    "totalitarismo":2,
    "marx":1,
    "engels":1,
    "social":1,

}

